#@url = https://8080-marcoweb-apiquiz20242-us2tnb4btx5.ws-us116.gitpod.io

@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgUXVpenplcyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzMwNzQ3OTY0fQ.leWf1DV4lExlSyJiAOYxTVE1v5fudxN9TX7U4fHrvKc

###
GET {{url}}/categorias
Authorization: Bearer {{token}}

###
GET {{url}}/categorias/10

###
POST {{url}}/categorias
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Conhecimentos Gerais"
}

###
DELETE {{url}}/categorias/5

###
PUT {{url}}/categorias/10
Content-Type: application/json

{
    "nome": "Arquitetura de APIs  - Alterado"
}