@url = https://8080-marcoweb-apiquiz20242-us2tnb4btx5.ws-us116.gitpod.io

###
GET {{url}}/categorias

###
GET {{url}}/categorias/10

###
POST {{url}}/categorias
Content-Type: application/json

{
    "nome": "Conhecimentos Gerais"
}

###
DELETE {{url}}/categorias/5

###
PUT {{url}}/categorias/10
Content-Type: application/json

{
    "nome": "Arquitetura de APIs  - Alterado"
}